<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DSH Launcher</AssemblyName>
    <RootNamespace>DshLauncher</RootNamespace>
    <ApplicationTitle>DSH Launcher</ApplicationTitle>
    <ApplicationIcon>Assets\DSHLauncher.ico</ApplicationIcon>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0.0</FileVersion>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\DSHLauncher.ico" />
    <None Remove="Assets\DeepSeek.ico" />
    <Resource Include="Assets\DSHLauncher.ico" />
    <Resource Include="Assets\DeepSeek.ico" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>
</Project>
